// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHs4k56DkMfOsbiP-aOzKX-2xyfi1_Bw',
    appId: '1:1005084329151:web:1e2da1b24bf583d3dfb20a',
    messagingSenderId: '1005084329151',
    projectId: 'socialapp-beae3',
    authDomain: 'socialapp-beae3.firebaseapp.com',
    storageBucket: 'socialapp-beae3.firebasestorage.app',
    measurementId: 'G-2QEC9ZW6TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVFYlML7juVbc_sck4IoRhVc4iBOd-QYU',
    appId: '1:1005084329151:android:2b07b0d915319b3bdfb20a',
    messagingSenderId: '1005084329151',
    projectId: 'socialapp-beae3',
    storageBucket: 'socialapp-beae3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6FCYuDGSCMbdN4zjqd6wK02u_rHdMms',
    appId: '1:1005084329151:ios:ba5fbd0c527c4eb0dfb20a',
    messagingSenderId: '1005084329151',
    projectId: 'socialapp-beae3',
    storageBucket: 'socialapp-beae3.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
